language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit -c tests/phpunit.xml.dist --colors --coverage-clover=build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
